### ISSUE TITLE
Please grant John, Randall and I access so we can continue maintaining this project.

### ISSUE THREAD

**Issue by inadarei** [npr/metalogger#19]
When you moved this from publicmediaplatform to npr, the maintainers of the project lost commit access to the project. Please restore it so we can continue maintaining this project here. 

Thank you

**Comment by scottsmith130** [comment]
Hey Irakli (@inadarei) sorry about that. A lot of permissions got reset when we moved repos. We'll get this fixed shortly (maybe by tomorrow).

**Comment by inadarei** [comment]
Thank you, @scottsmith130. I see that @milespj just sent an invitation. Much appreciated.

Happy holidays!
